// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmRJPlMOjimEGHYaKnLDpVxXUXFKfDJDQ',
    appId: '1:767117199089:web:649668958ad19f1df9cb50',
    messagingSenderId: '767117199089',
    projectId: 'reddit-clone-48257',
    authDomain: 'reddit-clone-48257.firebaseapp.com',
    storageBucket: 'reddit-clone-48257.appspot.com',
    measurementId: 'G-782E8DVSMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm4lKjCo1NEltCyKMqWvpHgaIfFU47zRo',
    appId: '1:767117199089:android:9d0875240aac755ef9cb50',
    messagingSenderId: '767117199089',
    projectId: 'reddit-clone-48257',
    storageBucket: 'reddit-clone-48257.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMLq3E163p0WuUB-XBjE_mqye6vfCwC7g',
    appId: '1:767117199089:ios:adbcf2581606fa47f9cb50',
    messagingSenderId: '767117199089',
    projectId: 'reddit-clone-48257',
    storageBucket: 'reddit-clone-48257.appspot.com',
    iosBundleId: 'com.example.flutterRedditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMLq3E163p0WuUB-XBjE_mqye6vfCwC7g',
    appId: '1:767117199089:ios:1ac61fff7b04abe1f9cb50',
    messagingSenderId: '767117199089',
    projectId: 'reddit-clone-48257',
    storageBucket: 'reddit-clone-48257.appspot.com',
    iosBundleId: 'com.example.flutterRedditClone.RunnerTests',
  );
}
